#!/usr/bin/php
<?php
include("../index.php"); // bootstrap ProcessWire

function listPage($page, $level = 0) {
        echo str_repeat("    ", $level) . $page->path . " (" . $page->id . ")" . "\n";
        foreach($page->children as $child) listPage($child, $level+1);
}
listPage($wire->pages->get("/")); // start at homepage